include:
  - board: seeeduino_xiao_ble
    shield: rommana_central_dongle dongle_display
  - board: seeeduino_xiao_ble
    shield: sweep_central_dongle dongle_display
    
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle
  - board: seeeduino_xiao_ble
    shield: settings_reset
